dependencies:
 # we need to tell brownie which GitHub repository to get chainlink from
 #- <organization/repot>@<version> 
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
 # we need to tell the brownie compiler what @chainlink means
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
networks:  ## will get a key-error if the network is missing from this list
  kovan:
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False    
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}